# Generated by Django 4.1.5 on 2023-01-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('worksite', models.CharField(blank=True, max_length=30, null=True)),
                ('passwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='worktiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userdata'))),
                ('date', models.DateField()),
                ('starth', models.IntegerField(max_length=23)),
                ('startm', models.IntegerField(max_length=59)),
                ('endh', models.IntegerField(max_length=23)),
                ('endm', models.IntegerField(max_length=59)),
                ('overtime', models.FloatField(blank=True, max_length=8.1, null=True)),
                ('flag', models.BooleanField()),
            ],
        ),
    ]
