# Generated by Django 4.1.5 on 2023-01-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktiem',
            name='endh',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worktiem',
            name='endm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worktiem',
            name='starth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worktiem',
            name='startm',
            field=models.IntegerField(),
        ),
    ]
